### ISSUE TITLE
Array and List backed HashRing implementations throw on removeNode

### ISSUE THREAD

**Issue by buritos** [vlingo/xoom-lattice#14]
`MD5*Ring` and `MurmurArrayHashRing` `excludeNode` always fail with `ArrayIndexOutOfBoundsException`. `nodeOf` also fails with the same exception when the ring is empty. From what I see it the exact same algorithm copied over to all of these.

There are ignored tests which currently fail for these here: https://github.com/vlingo/vlingo-lattice/pull/12

**Comment by VaughnVernon** [comment]
Long obsolete.
